In [2]:
#구 비율 데이터 만들기 -> PIH_MERGE만들기

In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np

In [2]:
sig_code = pd.read_csv('../Data/processing_data/2nd/busan_code.csv')

In [3]:
sig_code = sig_code[sig_code['DONG'].isna()].reset_index(drop=True)

In [4]:
sig_code = sig_code.drop(columns='DONG')

In [5]:
#불투수면 작업

In [6]:
#전국 데이터에서 부산 데이터를 뽑아냄 불투수면의 경우 법정동코드로 되어 있고 
# 부산의 법정동코드는 21로 시작하는데 부산의 '구' 데이터만 가져온다.
#busan_code = busan_code.rename(columns={'법정동코드':'CODE','n2':'ZONE','n3':'DONG'})

In [7]:
imper = pd.read_excel('../data/rawdata/imper_ratio_data.xlsx')
imper['코드'] = imper['코드'].apply(str)
imper = imper[imper['코드'].str.startswith('21')].reset_index(drop=True)
imper = imper.drop(index=0).reset_index(drop=True)
imper = imper.drop(columns=['코드','기준연도','불투수면 면적(㎢)'])
imper.rename(columns={'시도시군구':'ZONE', '불투수면 비율(%)':'IMP_SUR_RATIO',\
                              '행정구역면적(㎢)':'ZONE_AREA'}, inplace=True)
imper['ZONE_AREA'] = round(imper['ZONE_AREA'],2) * 10000000
imper['IMP_SUR_RATIO'] = round(imper['IMP_SUR_RATIO'],2)
PIH_merge = pd.merge(sig_code, imper, on='ZONE', how='left')

In [8]:
#맨홀작업

In [9]:
manhole = pd.read_excel("../Data/rawdata/manhole_data.xlsx", sheet_name="2-1_지역별 현황", header = 1)

In [10]:
manhole = manhole[manhole["행정구역"] == '부산광역시'][['Unnamed: 2', '합류식맨홀\n(개소)']].iloc[2:]

In [11]:
manhole.rename(columns={'Unnamed: 2':'ZONE', '합류식맨홀\n(개소)':'MANHOLES_COUNT'}, inplace=True)
manhole.reset_index(drop=True)
manhole['MANHOLES_COUNT'] = manhole['MANHOLES_COUNT'].astype(int)

In [12]:
PIH_merge = pd.merge(PIH_merge, manhole, on='ZONE', how='left')

In [13]:
PIH_merge

          CODE  ZONE  IMP_SUR_RATIO     ZONE_AREA  MANHOLES_COUNT
0   2611000000    중구          81.61  3.010000e+07             773
1   2614000000    서구          40.57  1.414000e+08            1308
2   2617000000    동구          57.92  1.009000e+08            2410
3   2620000000   영도구          45.77  1.463000e+08            1914
4   2623000000  부산진구          45.91  2.978000e+08            6581
5   2626000000   동래구          59.03  1.667000e+08            3165
6   2629000000    남구          51.82  2.728000e+08            3156
7   2632000000    북구          22.17  3.976000e+08            6842
8   2635000000  해운대구          27.63  5.232000e+08            8794
9   2638000000   사하구          38.20  4.711000e+08            8331
10  2641000000   금정구          18.94  6.573000e+08            3082
11  2644000000   강서구          24.36  1.848800e+09           12838
12  2647000000   연제구          62.32  1.215000e+08            1991
13  2650000000   수영구          61.44  1.035000e+08            1930
14  2653000000   사상구          40.23  3.625000e+08            5053
15  2671000000   기장군           7.70  2.198800e+09            3558

In [14]:
# #펌프작업
# pump_data1 = pd.read_csv('../data/rawdata/busan_pump_data.csv', encoding='euc-kr')
# pump_data2 = gpd.read_file('../Data/rawdata/FL_PUMP/FL_PUMP_SP.shp')
# pump_data1.iloc[29:31,0:1] = '금정구'
# pump_data1.iloc[26:27,0:1] = '연제구'
# code['CODE'] = code['CODE'].apply(str)
# code
# pump_data2 = pd.merge(code, pump_data2, left_on='CODE', right_on='ADM_CD', how='inner')
# pump_data2.shape
# pump_data2 = pump_data2.groupby(by='ZONE').count()['CODE']
# pump_data2.sum()
# pump_data1 = pump_data1.groupby(by='구군').count()['배수펌프장명']
# pump_data = pump_data1.add(pump_data2,fill_value=0)
# pump_data = pump_data.reset_index()
# pump_data.rename(columns={'index':'ZONE',0:'PUMP_COUNT'},inplace=True)
# pump_data['PUMP_COUNT'] = pump_data['PUMP_COUNT'].astype(int)
# pump_data
# PIH_merge = pd.merge(PIH_merge,pump_data,on='ZONE',how='left')
# PIH_merge = PIH_merge.fillna(0)
# PIH_merge
# PIH_merge['PUMP_RATIO'] = PIH_merge['PUMP_COUNT'] / PIH_merge['ZONE_AREA']

In [15]:
#침수빈도

In [16]:
df = pd.read_csv("../Data/processing_data/1st/busan_flood_geo.csv")
df1 = df.copy()
a = df1[["ZONE","F_BEGIN_DE"]]
b = a.copy()
b.drop_duplicates(["ZONE","F_BEGIN_DE"],inplace=True)
b.astype({"ZONE":str})

# 가중치 구하기
zone = ['연제구', '서구', '동구', '영도구', '부산진구', '동래구', '남구', '북구', '해운대구', '사하구',
       '금정구', '강서구', '수영구', '사상구', '기장군']
count = [4,1,1,2,1,1,1,1,3,5,1,3,4,1,1]
w = pd.DataFrame({"ZONE":zone,"COUNT":count})
bins = pd.DataFrame({"bin":w.groupby("COUNT").size()})
bins["percentage"]=round((bins["bin"]/bins["bin"].sum())*100,2)
bins["COUNT1"]=[1,2,3,4,5]
F_bin = pd.merge(w,bins,how="inner",left_on="COUNT",right_on="COUNT1")
F_bin.drop(["COUNT1","bin"],axis=1,inplace=True)
F_bin.rename(columns={"COUNT":"F_GRADE","percentage":"F_PERCENTAGE"},inplace=True)
F_bin
F_bin["F_WEIGHT"] = 1/F_bin["F_PERCENTAGE"]
F_bin

    ZONE  F_GRADE  F_PERCENTAGE  F_WEIGHT
0    연제구        4         13.33  0.075019
1    수영구        4         13.33  0.075019
2     서구        1         60.00  0.016667
3     동구        1         60.00  0.016667
4   부산진구        1         60.00  0.016667
5    동래구        1         60.00  0.016667
6     남구        1         60.00  0.016667
7     북구        1         60.00  0.016667
8    금정구        1         60.00  0.016667
9    사상구        1         60.00  0.016667
10   기장군        1         60.00  0.016667
11   영도구        2          6.67  0.149925
12  해운대구        3         13.33  0.075019
13   강서구        3         13.33  0.075019
14   사하구        5          6.67  0.149925

In [17]:
PIH_merge = pd.merge(PIH_merge, F_bin, on='ZONE', how='left')
PIH_merge = PIH_merge.fillna(0)

In [18]:
PIH_merge

,CODE,ZONE,IMP_SUR_RATIO,ZONE_AREA,MANHOLES_COUNT,F_GRADE,F_PERCENTAGE,F_WEIGHT
0,2611000000,중구,81.61,3.010000e+07,773,0.0,0.00,0.000000
1,2614000000,서구,40.57,1.414000e+08,1308,1.0,60.00,0.016667
2,2617000000,동구,57.92,1.009000e+08,2410,1.0,60.00,0.016667
3,2620000000,영도구,45.77,1.463000e+08,1914,2.0,6.67,0.149925
4,2623000000,부산진구,45.91,2.978000e+08,6581,1.0,60.00,0.016667
5,2626000000,동래구,59.03,1.667000e+08,3165,1.0,60.00,0.016667
6,2629000000,남구,51.82,2.728000e+08,3156,1.0,60.00,0.016667
7,2632000000,북구,22.17,3.976000e+08,6842,1.0,60.00,0.016667
8,2635000000,해운대구,27.63,5.232000e+08,8794,3.0,13.33,0.075019
9,2638000000,사하구,38.20,4.711000e+08,8331,5.0,6.67,0.149925
10,2641000000,금정구,18.94,6.573000e+08,3082,1.0,60.00,0.016667
11,2644000000,강서구,24.36,1.848800e+09,12838,3.0,13.33,0.075019
12,2647000000,연제구,62.32,1.215000e+08,1991,4.0,13.33,0.075019
13,2650000000,수영구,61.44,1.035000e+08,1930,4.0,13.33,0.075019
14,2653000000,사상구,40.23,3.625000e+08,5053,1.0,60.00,0.016667
15,2671000000,기장군,7.70,2.198800e+09,3558,1.0,60.00,0.016667

In [19]:
PIH_merge['MANHOLES_RATIO'] = PIH_merge['MANHOLES_COUNT'] * 1000 / PIH_merge['ZONE_AREA']

In [20]:
PIH_merge

,CODE,ZONE,IMP_SUR_RATIO,ZONE_AREA,MANHOLES_COUNT,F_GRADE,F_PERCENTAGE,F_WEIGHT,MANHOLES_RATIO
0,2611000000,중구,81.61,3.010000e+07,773,0.0,0.00,0.000000,0.025681
1,2614000000,서구,40.57,1.414000e+08,1308,1.0,60.00,0.016667,0.009250
2,2617000000,동구,57.92,1.009000e+08,2410,1.0,60.00,0.016667,0.023885
3,2620000000,영도구,45.77,1.463000e+08,1914,2.0,6.67,0.149925,0.013083
4,2623000000,부산진구,45.91,2.978000e+08,6581,1.0,60.00,0.016667,0.022099
5,2626000000,동래구,59.03,1.667000e+08,3165,1.0,60.00,0.016667,0.018986
6,2629000000,남구,51.82,2.728000e+08,3156,1.0,60.00,0.016667,0.011569
7,2632000000,북구,22.17,3.976000e+08,6842,1.0,60.00,0.016667,0.017208
8,2635000000,해운대구,27.63,5.232000e+08,8794,3.0,13.33,0.075019,0.016808
9,2638000000,사하구,38.20,4.711000e+08,8331,5.0,6.67,0.149925,0.017684
10,2641000000,금정구,18.94,6.573000e+08,3082,1.0,60.00,0.016667,0.004689
11,2644000000,강서구,24.36,1.848800e+09,12838,3.0,13.33,0.075019,0.006944
12,2647000000,연제구,62.32,1.215000e+08,1991,4.0,13.33,0.075019,0.016387
13,2650000000,수영구,61.44,1.035000e+08,1930,4.0,13.33,0.075019,0.018647
14,2653000000,사상구,40.23,3.625000e+08,5053,1.0,60.00,0.016667,0.013939
15,2671000000,기장군,7.70,2.198800e+09,3558,1.0,60.00,0.016667,0.001618

In [21]:
PIH_merge = PIH_merge.sort_values('ZONE').reset_index(drop=True)

In [22]:
PIH_merge

,CODE,ZONE,IMP_SUR_RATIO,ZONE_AREA,MANHOLES_COUNT,F_GRADE,F_PERCENTAGE,F_WEIGHT,MANHOLES_RATIO
0,2644000000,강서구,24.36,1.848800e+09,12838,3.0,13.33,0.075019,0.006944
1,2641000000,금정구,18.94,6.573000e+08,3082,1.0,60.00,0.016667,0.004689
2,2671000000,기장군,7.70,2.198800e+09,3558,1.0,60.00,0.016667,0.001618
3,2629000000,남구,51.82,2.728000e+08,3156,1.0,60.00,0.016667,0.011569
4,2617000000,동구,57.92,1.009000e+08,2410,1.0,60.00,0.016667,0.023885
5,2626000000,동래구,59.03,1.667000e+08,3165,1.0,60.00,0.016667,0.018986
6,2623000000,부산진구,45.91,2.978000e+08,6581,1.0,60.00,0.016667,0.022099
7,2632000000,북구,22.17,3.976000e+08,6842,1.0,60.00,0.016667,0.017208
8,2653000000,사상구,40.23,3.625000e+08,5053,1.0,60.00,0.016667,0.013939
9,2638000000,사하구,38.20,4.711000e+08,8331,5.0,6.67,0.149925,0.017684
10,2614000000,서구,40.57,1.414000e+08,1308,1.0,60.00,0.016667,0.009250
11,2650000000,수영구,61.44,1.035000e+08,1930,4.0,13.33,0.075019,0.018647
12,2647000000,연제구,62.32,1.215000e+08,1991,4.0,13.33,0.075019,0.016387
13,2620000000,영도구,45.77,1.463000e+08,1914,2.0,6.67,0.149925,0.013083
14,2611000000,중구,81.61,3.010000e+07,773,0.0,0.00,0.000000,0.025681
15,2635000000,해운대구,27.63,5.232000e+08,8794,3.0,13.33,0.075019,0.016808

In [23]:
PIH_merge.to_csv('../Data/processing_data/2nd/PIH_merge.csv', encoding='utf-8', index=False)

In [24]:
# 불투수면 가중치 계산

In [25]:
#df_positive = df[df.NUM >= 0].copy()
#df_positive['SQUARED'] = df_positive.NUM ** 2

In [26]:
imp_weight = PIH_merge['IMP_SUR_RATIO'].copy()

In [27]:
for idx,col in enumerate(PIH_merge['IMP_SUR_RATIO']):
    if col <= 15:
        imp_weight[idx] = col / 6.66
    elif col > 15 and col <= 25:
        imp_weight[idx] = col / (20 * 2)
    elif col > 25 and col <= 40:
        imp_weight[idx] = col / (13.33 * 3)
    elif col > 40 and col <= 55:
        imp_weight[idx] = col / (33.33 * 4)
    elif col > 55:
        imp_weight[idx] = col / (26.67 * 5)

In [28]:
PIH_merge['Impervious_Surface_Weight'] = imp_weight

In [29]:
PIH_merge

,CODE,ZONE,IMP_SUR_RATIO,ZONE_AREA,MANHOLES_COUNT,F_GRADE,F_PERCENTAGE,F_WEIGHT,MANHOLES_RATIO,Impervious_Surface_Weight
0,2644000000,강서구,24.36,1.848800e+09,12838,3.0,13.33,0.075019,0.006944,0.609000
1,2641000000,금정구,18.94,6.573000e+08,3082,1.0,60.00,0.016667,0.004689,0.473500
2,2671000000,기장군,7.70,2.198800e+09,3558,1.0,60.00,0.016667,0.001618,1.156156
3,2629000000,남구,51.82,2.728000e+08,3156,1.0,60.00,0.016667,0.011569,0.388689
4,2617000000,동구,57.92,1.009000e+08,2410,1.0,60.00,0.016667,0.023885,0.434346
5,2626000000,동래구,59.03,1.667000e+08,3165,1.0,60.00,0.016667,0.018986,0.442670
6,2623000000,부산진구,45.91,2.978000e+08,6581,1.0,60.00,0.016667,0.022099,0.344359
7,2632000000,북구,22.17,3.976000e+08,6842,1.0,60.00,0.016667,0.017208,0.554250
8,2653000000,사상구,40.23,3.625000e+08,5053,1.0,60.00,0.016667,0.013939,0.301755
9,2638000000,사하구,38.20,4.711000e+08,8331,5.0,6.67,0.149925,0.017684,0.955239
10,2614000000,서구,40.57,1.414000e+08,1308,1.0,60.00,0.016667,0.009250,0.304305
11,2650000000,수영구,61.44,1.035000e+08,1930,4.0,13.33,0.075019,0.018647,0.460742
12,2647000000,연제구,62.32,1.215000e+08,1991,4.0,13.33,0.075019,0.016387,0.467342
13,2620000000,영도구,45.77,1.463000e+08,1914,2.0,6.67,0.149925,0.013083,0.343309
14,2611000000,중구,81.61,3.010000e+07,773,0.0,0.00,0.000000,0.025681,0.611999
15,2635000000,해운대구,27.63,5.232000e+08,8794,3.0,13.33,0.075019,0.016808,0.690923

In [32]:
PIH_merge = PIH_merge[['CODE','ZONE','F_WEIGHT','MANHOLES_RATIO','Impervious_Surface_Weight']]

In [33]:
PIH_merge.to_csv('../Data/processing_data/2nd/PIH_weight_merge.csv', encoding='utf-8', index=False)