In [1]:
import pandas as pd

In [47]:
data = pd.read_excel('xycode.xlsx')

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3765 entries, 0 to 3764
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   구분         3764 non-null   object
 1   행정구역코드     3765 non-null   int64
 2   1단계        3765 non-null   object
 3   2단계        3746 non-null   object
 4   3단계        3496 non-null   object
 5   격자 X       3765 non-null   int64
 6   격자 Y       3765 non-null   int64
 7   경도(시)      3765 non-null   int64
 8   경도(분)      3765 non-null   int64
 9   경도(초)      3765 non-null   float64
 10  위도(시)      3765 non-null   int64
 11  위도(분)      3765 non-null   int64
 12  위도(초)      3765 non-null   float64
 13  경도(초/100)  3765 non-null   float64
 14  위도(초/100)  3765 non-null   float64
 15  위치업데이트     377 non-null    float64
dtypes: float64(5), int64(7), object(4)
memory usage: 470.8+ KB

In [49]:
data['CODE'] = data['행정구역코드'].apply(str)

In [56]:
busan_data = data[data['CODE'].str.startswith('26')]

In [57]:
busan_data = busan_data[['2단계','3단계','격자 X', '격자 Y', 'CODE']]

In [58]:
busan_data = busan_data.fillna(0)
busan_data = busan_data[busan_data['3단계']==0]

In [61]:
busan_data = busan_data.drop(columns='3단계')
busan_data = busan_data.drop(index=451)
busan_data

      2단계  격자 X  격자 Y        CODE
452    중구    97    74  2611000000
462    서구    97    74  2614000000
476    동구    98    75  2617000000
489   영도구    98    74  2620000000
501  부산진구    97    75  2623000000
522   동래구    98    76  2626000000
536    남구    98    75  2629000000
554    북구    96    76  2632000000
568  해운대구    99    75  2635000000
587   사하구    96    74  2638000000
604   금정구    98    77  2641000000
621   강서구    96    76  2644000000
630   연제구    98    76  2647000000
643   수영구    99    75  2650000000
654   사상구    96    75  2653000000
667   기장군   100    77  2671000000

In [64]:
busan_data = busan_data.rename(columns={'2단계':'ZONE','격자 X':'X','격자 Y' : 'Y'})

In [65]:
busan = busan_data.reset_index()
busan = busan.drop(columns='index')

In [66]:
base_dong = pd.read_csv('./base_dong.csv')

In [67]:
base_geo_data = pd.merge(base_dong,busan,on='ZONE', how='left')

In [68]:
base_geo_data

,Unnamed: 0,ADM_CD,ZONE,Dong,SLOPE_AVG,HIGH,PUMP_RATIO,IMP_SUR_RATIO,MANHOLES_RATIO,X,Y,CODE
0,0,2644012000,강서구,눌차동,22.5,9.11,1.190000e-07,24.36,0.006944,96,76,2644000000
1,1,2644010400,강서구,명지동,1.0,1.55,1.190000e-07,24.36,0.006944,96,76,2644000000
2,2,2644010100,강서구,대저1동,1.0,1.77,1.190000e-07,24.36,0.006944,96,76,2644000000
3,3,2644010200,강서구,대저2동,1.0,1.18,1.190000e-07,24.36,0.006944,96,76,2644000000
4,4,2644011900,강서구,성북동,11.0,1.31,1.190000e-07,24.36,0.006944,96,76,2644000000
5,5,2641010800,금정구,장전동,4.5,15.16,3.040000e-08,18.94,0.004689,98,77,2641000000
6,6,2641010900,금정구,부곡동,4.5,12.94,3.040000e-08,18.94,0.004689,98,77,2641000000
7,7,2641010700,금정구,구서동,11.0,24.95,3.040000e-08,18.94,0.004689,98,77,2641000000
8,8,2641010200,금정구,노포동,11.0,63.77,3.040000e-08,18.94,0.004689,98,77,2641000000
9,9,2641010100,금정구,두구동,1.0,61.97,3.040000e-08,18.94,0.004689,98,77,2641000000
10,10,2641010400,금정구,남산동,4.5,36.22,3.040000e-08,18.94,0.004689,98,77,2641000000
11,11,2641011100,금정구,금사동,4.5,6.88,3.040000e-08,18.94,0.004689,98,77,2641000000
12,12,2671033000,기장군,철마면,4.5,77.86,1.360000e-08,7.70,0.001618,100,77,2671000000
13,13,2671025000,기장군,기장읍,4.5,4.24,1.360000e-08,7.70,0.001618,100,77,2671000000
14,14,2671025300,기장군,장안읍,4.5,4.92,1.360000e-08,7.70,0.001618,100,77,2671000000
15,15,2671025600,기장군,정관읍,4.5,35.56,1.360000e-08,7.70,0.001618,100,77,2671000000
16,16,2671031000,기장군,일광면,4.5,2.03,1.360000e-08,7.70,0.001618,100,77,2671000000
17,17,2629010700,남구,용호동,1.0,3.77,2.570000e-07,51.82,0.011569,98,75,2629000000
18,18,2617010400,동구,범일동,1.0,2.96,1.980000e-07,57.92,0.023885,98,75,2617000000
19,19,2626010200,동래구,안락동,11.0,5.14,2.400000e-07,59.03,0.018986,98,76,2626000000
20,20,2626010800,동래구,온천동,1.0,10.81,2.400000e-07,59.03,0.018986,98,76,2626000000
21,21,2626010600,동래구,수안동,1.0,4.69,2.400000e-07,59.03,0.018986,98,76,2626000000
22,22,2626010900,동래구,사직동,3.0,6.53,2.400000e-07,59.03,0.018986,98,76,2626000000
23,23,2626010700,동래구,명륜동,1.0,7.64,2.400000e-07,59.03,0.018986,98,76,2626000000
24,24,2623011000,부산진구,가야동,4.5,33.43,0.000000e+00,45.91,0.022099,97,75,2623000000
25,25,2632010500,북구,구포동,11.0,9.97,1.510000e-07,22.17,0.017208,96,76,2632000000
26,26,2632010400,북구,덕천동,45.0,171.04,1.510000e-07,22.17,0.017208,96,76,2632000000
27,27,2632010200,북구,화명동,15.0,32.29,1.510000e-07,22.17,0.017208,96,76,2632000000
28,28,2653010300,사상구,덕포동,1.0,5.81,3.860000e-07,40.23,0.013939,96,75,2653000000
29,29,2653010600,사상구,주례동,1.0,1.36,3.860000e-07,40.23,0.013939,96,75,2653000000
30,30,2653010400,사상구,괘법동,1.0,2.76,3.860000e-07,40.23,0.013939,96,75,2653000000
31,31,2653010500,사상구,감전동,1.0,2.44,3.860000e-07,40.23,0.013939,96,75,2653000000
32,32,2638010300,사하구,하단동,1.0,2.40,1.490000e-07,38.20,0.017684,96,74,2638000000
33,33,2638010500,사하구,장림동,1.0,1.98,1.490000e-07,38.20,0.017684,96,74,2638000000
34,34,2638010100,사하구,괴정동,12.5,26.51,1.490000e-07,38.20,0.017684,96,74,2638000000
35,35,2638010700,사하구,구평동,1.0,2.52,1.490000e-07,38.20,0.017684,96,74,2638000000
36,36,2638010600,사하구,다대동,1.0,2.94,1.490000e-07,38.20,0.017684,96,74,2638000000
37,37,2638010800,사하구,감천동,8.5,6.42,1.490000e-07,38.20,0.017684,96,74,2638000000
38,38,2614012400,서구,암남동,11.0,1.92,0.000000e+00,40.57,0.009250,97,74,2614000000
39,39,2650010300,수영구,민락동,4.5,2.01,0.000000e+00,61.44,0.018647,99,75,2650000000
40,40,2650010200,수영구,수영동,1.0,3.47,0.000000e+00,61.44,0.018647,99,75,2650000000
41,41,2650010100,수영구,망미동,11.0,5.80,0.000000e+00,61.44,0.018647,99,75,2650000000
42,42,2650010400,수영구,광안동,4.5,3.38,0.000000e+00,61.44,0.018647,99,75,2650000000
43,43,2650010500,수영구,남천동,4.5,3.12,0.000000e+00,61.44,0.018647,99,75,2650000000
44,44,2647010200,연제구,연산동,1.0,3.43,4.120000e-07,62.32,0.016387,98,76,2647000000
45,45,2647010100,연제구,거제동,4.5,5.75,4.120000e-07,62.32,0.016387,98,76,2647000000
46,46,2620012000,영도구,청학동,1.0,3.18,0.000000e+00,45.77,0.013083,98,74,2620000000
47,47,2620010700,영도구,남항동3가,1.0,1.94,0.000000e+00,45.77,0.013083,98,74,2620000000
48,48,2620012100,영도구,동삼동,45.0,31.30,0.000000e+00,45.77,0.013083,98,74,2620000000
49,49,2635010500,해운대구,우동,1.0,3.47,2.100000e-07,27.63,0.016808,99,75,2635000000
50,50,2635010200,해운대구,석대동,1.0,6.28,2.100000e-07,27.63,0.016808,99,75,2635000000
51,51,2635010100,해운대구,반송동,4.5,3.40,2.100000e-07,27.63,0.016808,99,75,2635000000
52,52,2635010300,해운대구,반여동,4.5,2.67,2.100000e-07,27.63,0.016808,99,75,2635000000
53,53,2635010600,해운대구,중동,4.5,6.67,2.100000e-07,27.63,0.016808,99,75,2635000000
54,54,2635010800,해운대구,송정동,4.5,26.90,2.100000e-07,27.63,0.016808,99,75,2635000000
55,55,2617053000,동구,초량제3동,1.0,4.00,1.980000e-07,57.92,0.023885,98,75,2617000000

In [69]:
base_geo_data = base_geo_data.drop(columns=['Unnamed: 0','CODE'])

In [70]:
base_geo_data.shape

(56, 10)

In [71]:
base_geo_data.to_csv('base_data.csv', encoding='utf-8')

In [73]:
busan_data = busan_data.reset_index()
busan_data = busan_data.drop(columns='index')
busan_data

    ZONE    X   Y        CODE
0     중구   97  74  2611000000
1     서구   97  74  2614000000
2     동구   98  75  2617000000
3    영도구   98  74  2620000000
4   부산진구   97  75  2623000000
5    동래구   98  76  2626000000
6     남구   98  75  2629000000
7     북구   96  76  2632000000
8   해운대구   99  75  2635000000
9    사하구   96  74  2638000000
10   금정구   98  77  2641000000
11   강서구   96  76  2644000000
12   연제구   98  76  2647000000
13   수영구   99  75  2650000000
14   사상구   96  75  2653000000
15   기장군  100  77  2671000000

In [74]:
busan_data.to_csv('./xycode.csv', encoding='utf-8')